---
layout: post
title: "手写 Promise"
date: 2020-10-13 00:00:00
categories: promise js
---

得，该来的还是来了...

[工业聚](https://github.com/Lucifier129)在他的[《100 行代码实现 Promises/A+ 规范》](https://mp.weixin.qq.com/s/qdJ0Xd8zTgtetFdlJL3P1g) 中说，*“即便成功实现 Promises/A+ 规范，也不一定比没实现过的开发者，更善于使用 Promises 特性。”*

所以我一直拿这个当借口不想写。但是~~生活所迫~~面试官又不管...

非 Promises/A+，但是估计面试够用。

> 话说，原来 Promises/A+ 没有关于 `catch` 和 `all` 等方法的规定

```js
const isFunction = (e) => typeof e === 'function';

const PENDING = 'pending';
const FULFILLED = 'fulfilled';
const REJECTED = 'rejected';

function Lie(f) {
  this.result = null; // resolve 时为 value，reject 时为 reason
  this.state = PENDING;
  this.callbacks = [];

  // 创建实例时传入的 resolve/reject 执行时，状态的变化就确定了
  // 不是 FULFILLED 就是 REJECTED
  const onFulfilled = (value) => transition(this, FULFILLED, value);
  const onRejected = (reason) => transition(this, REJECTED, reason);

  try {
    f(onFulfilled, onRejected);
  } catch (error) {
    onRejected(error);
  }
}

Lie.prototype.then = function (onFulfilled, onRejected) {
  // 为了链式调用，then 需要返回一个 promise
  return new this.constructor((resolve, reject) => {
    const callback = {
      // 用户自定义的回调
      onFulfilled,
      onRejected,
      // promise 自己的回调
      resolve,
      reject,
    };
    if (this.state === PENDING) {
      // then 的用途之一是添加新的回调函数
      this.callbacks.push(callback);
    } else {
      setTimeout(() => runCallback(callback, this.state, this.result), 0);
    }
  });
};

Lie.prototype.catch = function (onRejected) {
  return this.then(null, onRejected);
};

const transition = (promise, state, result) => {
  if (promise.state !== PENDING) return;

  promise.state = state;
  promise.result = result;
  // setTimeout 的原因是规范里有这么一句
  // onFulfilled or onRejected must not be called
  // until the execution context stack contains only platform code.
  // 见工业聚的文章
  setTimeout(() => {
    const { callbacks, state, result } = promise;
    // 挨个取出回调函数并执行
    while (callbacks.length) runCallback(callbacks.shift(), state, result);
  }, 0);
};

const runCallback = (callback, state, result) => {
  const {
    onFulfilled, onRejected,
    resolve, reject,
  } = callback;
  try {
    if (state === FULFILLED) {
      // 如果有自定义回调就执行，不然就只执行 promise 默认的回调
      isFunction(onFulfilled) ? resolve(onFulfilled(result)) : resolve(result);
    } else if (state === REJECTED) {
      isFunction(onRejected) ? resolve(onRejected(result)) : reject(result);
    }
  } catch (error) {
    reject(error);
  }
};

Lie.all = function (promises) {
  return new this((resolve, reject) => {
    if (!Array.isArray(promises)) reject('type error');
    const result = [];
    promises.forEach((p) => {
      p.then((res) => {
        result.push(res);
        if (result.length === promises.length) resolve(result);
      }).catch(reject);
    });
  });
};

Lie.race = function (promises) {
  return new this((resolve, reject) => {
    if (!Array.isArray(promises)) reject('type error');
    let done = false;
    promises.forEach((p) => {
      p.then((res) => {
        if (!done) {
          done = true;
          resolve(res);
        }
      }).catch((err) => {
        if (!done) {
          done = true;
          reject(err);
        }
      });
    });
  });
};

// 测试一下

new Lie((resolve, reject) => {
  setTimeout(() => {
    resolve(1);
  }, 1000);
})
  .then((res) => {
    console.log('then1', res);
    return 2;
  })
  .then()
  .then((res) => {
    console.log('then3', res);
    throw 3;
  })
  .catch((err) => {
    console.error('catch', err);
  });

new Lie((resolve, reject) => {
  setTimeout(() => {
    reject(2);
  }, 1000);
})
  .then(console.log)
  .catch(console.error);

const p1 = new Lie((resolve) => {
  setTimeout(() => {
    resolve(1);
  }, 500);
});
const p2 = new Lie((resolve) => {
  setTimeout(() => {
    resolve(2);
  }, 1000);
});
const p3 = new Lie((resolve, reject) => {
  setTimeout(() => {
    reject(3);
  }, 500);
});
const task1 = [p1, p2];
const task2 = [p3, p2];
Lie.all(task1).then(console.log).catch(console.error);
Lie.all(task2).then(console.log).catch(console.error);
Lie.race(task1).then(console.log).catch(console.error);
```
